import React from "react";
import Header from "../components/header/Header";
import "../globals.css"; // Add any global styles here
import CardComp from "../components/content/cardComp";
import TopHeader from "../components/header/TopHeader";
import ChartTestComp from "../components/content/ChartTestComp";
import LineChartComp from "../components/content/LineChartComp";
import Visual1Comp from "../components/content/Visual1Comp";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={"body"}>
        <Header />
        {children}

        <div className="grid lg:grid-cols-10 px-8 splashCard">

          <div className="card md:w-96vw bg-base-100 shadow-xl m-2 lg:col-start-1 lg:col-span-2">
            <CardComp name="About" dropdownItems={["1", "2"]} linkUrl="/link"></CardComp>
          </div>

          <div className="lg:col-start-3 lg:col-span-8">
          <div class="grid lg:grid-rows-8 lg:grid-flow-row gap-4">

            <div className="card md:w-96vw bg-base-100 shadow-xl m-2 lg:row-start-1 lg:row-span-4">
            <CardComp name="About" dropdownItems={["1", "2"]} linkUrl="/link"></CardComp>
            <div className="lg:grid lg:grid-cols-2">
            <div className="lg:col-span-1 lg:col-start-1">
                <LineChartComp></LineChartComp>
              </div>
              <div className="lg:col-span-1 lg:col-start-2">
                <Visual1Comp></Visual1Comp>
              </div>
            </div>
            </div>
            
            <div className="lg:row-span-2 lg:row-start-5">
              <div className="grid lg:grid-cols-2 ">
                <div className="card md:w-96vw bg-base-100 shadow-xl m-2  lg:col-start-1 lg:col-span-1">
                  <CardComp name="About" dropdownItems={["1", "2"]} linkUrl="/link"></CardComp>
                </div>
                <div className="card md:w-96vw bg-base-100 shadow-xl m-2  lg:col-start-2 lg:col-span-1">
                  <CardComp name="About" dropdownItems={["1", "2"]} linkUrl="/link"></CardComp>
                </div>
              </div>
            </div>

            <div className="lg:row-span-2 lg:row-start-7">
              <div className="grid lg:grid-cols-2 ">
                <div className="card md:w-96vw bg-base-100 shadow-xl m-2  lg:col-start-1 lg:col-span-1">
                  <CardComp name="About" dropdownItems={["1", "2"]} linkUrl="/link"></CardComp>
                </div>
                <div className="card md:w-96vw bg-base-100 shadow-xl m-2  lg:col-start-2 lg:col-span-1">
                  <CardComp name="About" dropdownItems={["1", "2"]} linkUrl="/link"></CardComp>
                </div>
              </div>
            </div>

          </div>
          </div>

        </div>

        {/* Top header */}
        <TopHeader />
      </body>
    </html>
  );
}
