import React from "react";
import Header from "./components/header/Header";
import "./globals.css"; // Add any global styles here
import CardComp from "./components/content/cardComp";
import TopHeader from "./components/header/TopHeader";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={"body"}>
        <Header />
        {children}

        <div className="grid grid-cols-1 px-8 splashCard">
          <div className="card md:w-96vw bg-base-100 shadow-xl m-4">
            <CardComp name="About" dropdownItems={["1", "2"]} linkUrl="/link"></CardComp>
          </div>
        </div>

        <div className=" grid grid-cols-1 lg:grid-cols-2 px-8">

          <div className="card md:w-96vw bg-base-100 shadow-xl m-4">
            <CardComp name="About" dropdownItems={["1", "2"]} linkUrl="/link"></CardComp>
          </div>
          <div className="card md:w-96vw bg-base-100 shadow-xl m-4">
            <CardComp name="About" dropdownItems={["1", "2"]} linkUrl="/link"></CardComp>
          </div>
          <div className="card md:w-96vw bg-base-100 shadow-xl m-4">
            <CardComp name="About" dropdownItems={["1", "2"]} linkUrl="/link"></CardComp>
          </div>
          <div className="card md:w-96vw bg-base-100 shadow-xl m-4">
            <CardComp name="About" dropdownItems={["1", "2"]} linkUrl="/link"></CardComp>
          </div>

        </div>

        {/* Top header */}
        <TopHeader />
      </body>
    </html>
  );
}
